spring.application.name=demo

# ERPNext API Configuration
# erpnext.api.base-url=http://erpnext.localhost:8000
# erpnext.api.login-endpoint=/api/method/login


# Configuration ERPNext
erpnext.api.url=http://erpnext.localhost:8000
erpnext.api.login-endpoint=/api/method/login
# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false 
logging.level.org.thymeleaf=DEBUG